name: Publish package

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Publish
    concurrency: publish
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
      - uses: matteo4diani/poetry-semantic-release@main
        name: Semantic Release
        id: release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pypi-token: ${{ secrets.PYPI_TOKEN }}
          main-branch: master
          python-version: 3.11
    outputs:
      released: ${{ steps.release.outputs.released }}
